### ISSUE TITLE
 Unable to import MONSTER HUNTER RISE mesh

### ISSUE THREAD

**Issue by Poooaai** [NSACloud/RE-Mesh-Editor#1]
Hello As my title says Blender Unable to import mesh I would like to ask if there is any solution?
My blender 4.1
Attach pictures
![螢幕擷取畫面 2024-05-28 193612](https://github.com/NSACloud/RE-Mesh-Editor/assets/163369341/29bcb8a0-1349-475d-bbc3-fe451a01dece)
Sorry, my English is not good, so I have to use machine translation

**Comment by NSACloud** [comment]
It should be fixed now in V0.14. 

You can update the addon from Edit > Preferences > Addons > RE Mesh Editor > Check For Update.

**Comment by Poooaai** [comment]
Already successfully imported Thank you
