### ISSUE TITLE
SCN position data

### ISSUE THREAD

**Issue by speaker-60** [NSACloud/RE-Mesh-Editor#3]
Dont know if there is a better place to talk about this as this isnt an issue more of a feature request
Im attempting to import RE2 and Re3 maps so i can make a more fleshed out version of raccoon city, recreating missing areas from the original and other games set in raccoon city just for fun

So far iv tried the max script which dosnt load in half of the objects, which is actually an issue with the noesis part of the script but it basically results in over 50% of objects being missing

Iv been using instead the Rsz Tool so i can read the scn files and see the position data then i just load the objects in using this plugin and make an instance and set it to said position data. Its a very slow process and a major issue is that the Rsz tool dosnt show correct rotation values
![image](https://github.com/user-attachments/assets/d44144ea-350e-4d46-ad46-3ea5cafe70e4)
All rotation data are shown as some sort of 0.xxxxx value so in a 360 angle rotation these values are useless
Im guessing there translated wrong to the wrong unit type or something, so im having to just guess what the rotations are by looking at it ingame again making a very slow process
![image](https://github.com/user-attachments/assets/ac8c8f33-f08a-4c0f-bb20-c2ab7162fcc8)
Iv gotten so far already

So i was wondering about adding in a scn feature
The way iv been building out the map is i import the object with this plugin and i rename the folder it creates, i then use the 'instance to scene' on this collection to create instance copies
![image](https://github.com/user-attachments/assets/0d72d037-d064-4ff2-92a1-06ceb9ea5bfe)
I then position these copies

So what would be good is a import option for scn, when you select that option you have a sidebar where you set a object search parameter
For this example i set it to 'roadbarricade01a', it searches for a collection of this name and makes an instance of it, it then searches the scn for any object containing that name
![image](https://github.com/user-attachments/assets/fa1ca092-403f-4801-8f47-a9cd30bf3e16)
and then uses the transform data to position that instance, it repeats the search in the scn for more of the same object 
What you get is positioned collection instances of you selected object

This isnt the fastest way to do map importing but i thought it might be the simplest way to setup coding wise
If you can allow for multiple scn selection then we could put all the scn's into one folder and get the import to go through all of them so for each object we make a positioned instance of it for the whole game world

I don't intend to import this into the game so i dont know how this feature would work for that use but just to be able to import the map abit more easily then what im having to do currently would be perfect

**Comment by NSACloud** [comment]
I've been working on a map editor for blender for a long time, I still need to rewrite parts of it and fix collision exporting but I'll probably release it once MH Wilds is out.


![image](https://github.com/user-attachments/assets/3b1b4232-3af6-4298-8e5b-2c542ed4b869)
![image](https://github.com/user-attachments/assets/572da604-2f66-45c1-9c13-9bd38baa3d37)
![image](https://github.com/user-attachments/assets/192b5c10-3fad-43f1-83d9-ab7ec7d28d5d)

**Comment by NSACloud** [comment]
Maybe some time after the wilds beta, re2 is barely functional and 3 isn't supported yet. I have other tools I want to focus on for now, so it might be a while.

**Comment by speaker-60** [comment]
Alright, in the meantime do you have any suggestions on how i can obtain the rotations for objects 
As the Rsz tool dosnt show them properly

Ill probably continue with the map section i was doing for now but trying to figure out these rotations by eye is super annoying

**Comment by NSACloud** [comment]
They're quaternion rotations, you should just be able to copy and paste them into blender. Keep in mind the game is XYZW and blender is WXYZ. You also might need to rotate it 90 degrees on the x axis

**Comment by speaker-60** [comment]
Ah i see thankyou for that never used or needed this sort of thing so i didnt even know about it
I see the option in blender to set it to quaternion i kinda ignored/didnt realize

Thanks for teaching me that, for now i can finish up what i was doing manually but looking forward to your tool in the future :D
