### ISSUE TITLE
Scripting usage

### ISSUE THREAD

**Issue by 09williamsad** [NSACloud/RE-Mesh-Editor#8]
Blender importers can usually be run from the command/script window.
This is good for operations like batch conversion of multiple files.

However, I have not been able to get this working for re-mesh.

With most importers, the below should trigger the importer to load a file.
"import bpy
import os
bpy.ops.re_mesh.importfile(filepath="C:/Users/adamw/Downloads/MHWs/natives/stm/art/model/character/ch00/000/0000/ch00_000_0000.mesh.240820143")"

With RE Mesh it is accepting the filepath argument, but no action occurs after that and no mesh is imported.
"RE Mesh Editor V0.34
Blender Version 4.2.1
https://github.com/NSACloud/RE-Mesh-Editor
Info: Imported RE Mesh file."

I have not been able to figure out why.
Additionally I am still trying to call the texture importer in a way that is not using drag and drop.

**Comment by NSACloud** [comment]
The filepath argument isn't used, it uses the files and directory argument. Add an info window and import a file, it'll show you the arguments. It's that way to allow for multi file imports.

**Comment by 09williamsad** [comment]
Thank you for the information.
I did not think the directory and file arguments had to be specified seperately.
"import bpy
import os
bpy.ops.re_mesh.importfile(directory="C:/Users/adamw/Downloads/MHWs/natives/stm/art/model/character/ch00/000/0000/", files=[{"name":"ch00_000_0000.mesh.240820143"}])"

Do you have any pointers for the texture conversion by script instead of drag and drop?
I have not found a wall to call it yet.

**Comment by NSACloud** [comment]
It should be the same as mesh import except with `bpy.ops.re_tex.convert_tex_dds_files()`

**Comment by 09williamsad** [comment]
Thank you
